USE JOIN_TEST;

SELECT * FROM RESERVATION
INNER JOIN CUSTOMER
ON RESERVATION.NAME = CUSTOMER.NAME;

# LEFT JOIN
SELECT * FROM RESERVATION R
LEFT JOIN CUSTOMER C
ON R.NAME = C.NAME;

# RIGHT JOIN
SELECT * FROM RESERVATION R
RIGHT JOIN CUSTOMER C
ON R.NAME = C.NAME;