CREATE DATABASE TYPETEST;

USE TYPETEST;
SHOW TABLES;
CREATE TABLE TYPE_PRACTICE(
	ID INT,
    TYPE_NAME VARCHAR(30),
    TYPE_DETAIL INT
);

DESC TYPE_PRACTICE;

INSERT INTO TYPE_PRACTICE(ID, TYPE_NAME, TYPE_DETAIL)
VALUES(1, '숫자타입', 2147483648);

SELECT * FROM TYPE_PRACTICE;

ALTER TABLE TYPE_PRACTICE
MODIFY COLUMN TYPE_DETAIL BIGINT;

ALTER TABLE TYPE_PRACTICE
MODIFY COLUMN TYPE_DETAIL DECIMAL(5, 2);

ALTER TABLE TYPE_PRACTICE
ADD TEST_TYPE DECIMAL(5, 2);

INSERT INTO TYPE_PRACTICE(ID, TYPE_NAME, TYPE_DETAIL, TEST_TYPE, TEXT_TYPE, LONG_TEXT)
VALUES(1, '데시멀타입', 199.99, 999.22, 'ABCDEFGHI', '간단하게 써보자 정말 많이써보자 길게써보자 많이써보자 할말이 없지만 많이 써보자');

ALTER TABLE TYPE_PRACTICE
ADD TEXT_TYPE CHAR(30);

ALTER TABLE TYPE_PRACTICE
ADD LONG_TEXT TEXT;

ALTER TABLE TYPE_PRACTICE
ADD COLUMN SET_TEST SET('수업', '학교수업', '집에가고싶다');

INSERT INTO TYPE_PRACTICE(TYPE_NAME, SET_TEST)
VALUES('SET 테스트', 1);

CREATE TABLE DATETEST(
	ID INT,
    NAME DATE
);

INSERT INTO DATETEST(ID, NAME)
VALUES(1, '2025-03-19');

SELECT * FROM DATETEST;

SELECT * FROM TYPE_PRACTICE
WHERE TYPE_DETAIL BETWEEN 1 AND 405;

SELECT * FROM TYPE_PRACTICE
WHERE TYPE_DETAIL NOT IN (200, 1);

SELECT CASE 1234
	WHEN 0 THEN '안녕'
    WHEN 1 THEN '잘가'
    ELSE '???'
END;

SELECT IF(0 < 1, 'YES', 'NO');

