CREATE DATABASE PRACTICE_20250328;

USE PRACTICE_20250328;

CREATE TABLE RESERVATION(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RESERVEDATE DATE,
    ROOMNUM INT
);

INSERT INTO RESERVATION
VALUES
(1, '홍길동', '2016-01-05', 2014),
(2, '임꺽정', '2016-02-12', 918);

SELECT * FROM RESERVATION;

SHOW INDEX FROM RESERVATION;

# 인덱스 설정
CREATE INDEX NAMEIDX
ON RESERVATION (NAME);

# 인덱스 수정방법
ALTER TABLE RESERVATION
ADD INDEX TEST (ROOMNUM);

# 인덱스 삭제
ALTER TABLE RESERVATION
DROP INDEX NAMEIDX;

# LIMIT
SELECT * FROM RESERVATION
ORDER BY RESERVEDATE DESC
LIMIT 10;

SELECT * FROM RESERVATION
LIMIT 2 OFFSET 2;