START TRANSACTION;

INSERT INTO ORDERS(ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_AMOUNT)
VALUES(107, 1, '2025-07-01', 300);

UPDATE PRODUCTS
SET PRICE = 900
WHERE PRODUCT_ID = 201;

COMMIT;
ROLLBACK;

SELECT * FROM ORDERS WHERE ORDER_ID = 107;
SELECT * FROM PRODUCTS WHERE PRODUCT_ID = 201;

CALL UPDATECUSTOMERGRADE(1);