CREATE DATABASE JOIN_TEST;
USE JOIN_TEST;

CREATE TABLE RESERVATION(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RESERVEDATE DATE,
    ROOMNUM INT
);

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    AGE INT,
    ADDRESS VARCHAR(255)
);

INSERT INTO RESERVATION
VALUES(1, '홍길동', '2016-01-05', 2014);
INSERT INTO RESERVATION
VALUES(2, '임꺽정', '2016-02-12', 918);
INSERT INTO RESERVATION
VALUES(3, '장길산', '2016-01-16', 1208);
INSERT INTO RESERVATION
VALUES(4, '홍길동', '2016-03-17', 504);

INSERT INTO CUSTOMER
VALUES(1, '홍길동', 17, '서울');
INSERT INTO CUSTOMER
VALUES(2, '임꺽정', 11, '인천');
INSERT INTO CUSTOMER
VALUES(3, '장길산', 13, '서울');
INSERT INTO CUSTOMER
VALUES(4, '전우치', 17, '수원');

DESC RESERVATION;
DESC CUSTOMER;
SELECT * FROM RESERVATION;
SELECT * FROM CUSTOMER;