CREATE database TEST_0326;

USE TEST_0326;

CREATE TABLE RESERVATION(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RESERVEDATE DATE,
    ROOMNUM INT
);

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    AGE INT,
    ADDRESS VARCHAR(255)
);

INSERT INTO RESERVATION
VALUES(1, '홍길동', '2016-01-05', 2014);
INSERT INTO RESERVATION
VALUES(2, '임꺽정', '2016-02-12', 918);
INSERT INTO RESERVATION
VALUES(3, '장길산', '2016-01-16', 1208);
INSERT INTO RESERVATION
VALUES(4, '홍길동', '2016-03-17', 504);

INSERT INTO CUSTOMER
VALUES(1, '홍길동', 17, '서울');
INSERT INTO CUSTOMER
VALUES(2, '임꺽정', 11, '인천');
INSERT INTO CUSTOMER
VALUES(3, '장길산', 13, '서울');
INSERT INTO CUSTOMER
VALUES(4, '전우치', 17, '수원');

SELECT * FROM RESERVATION;
SELECT * FROM CUSTOMER;

SELECT *
FROM RESERVATION
UNION
SELECT *
FROM CUSTOMER;

SELECT * FROM RESERVATION
INNER JOIN CUSTOMER
ON RESERVATION.NAME = CUSTOMER.NAME;

SELECT ID, RESERVEDATE, ROOMNUM, NAME
FROM RESERVATION
WHERE NAME IN (SELECT NAME
			   FROM CUSTOMER
               WHERE ADDRESS = '서울');
               
# 특정 문자열 검색
SELECT LOCATE('안녕', '안녕하세요');
SELECT LOCATE('ABC', 'ABCDEFGHIJKABC', 4);

# 문자열 추출
SELECT LEFT('MySQL PHP HTML JAVA', 5),
	   RIGHT('MySQL PHP HTML JAVA', 4);

# 대소문자 변경
SELECT LOWER('MySQL PHP HTML JAVA');
SELECT UPPER('MySQL PHP HTML JAVA');

# 문자열 다듬기
SELECT TRIM('        !!!MySQL PHP HTML JAVA!!!          ');
SELECT TRIM(LEADING '!' FROM '!!!MySQL PHP HTML JAVA!!!');
SELECT TRIM(TRAILING '!' FROM '!!!MySQL PHP HTML JAVA!!!');

# 날짜 관련
SELECT NOW(),
CURDATE(),
CURTIME();

SELECT DATE('2025-03-25 12:34:56'),
MONTH('2025-03-25 12:34:56'),
DAY('2025-03-25 12:34:56'),
HOUR('12:34:56'),
MINUTE('12:34:56'),
SECOND('12:34:56');

SELECT MONTHNAME('2025-03-25'),
DAYNAME('2025-03-25');

SELECT DAYOFMONTH('2025-03-25'),
DAYOFWEEK('2025-03-25'),
DAYOFYEAR('2025-03-25');

#-------------------------------------------
SELECT AGE, COUNT(*) AS NUMOFCUSTOMER
FROM CUSTOMER
GROUP BY AGE;

# 실행 안됨
-- SELECT ADDRESS, NAME, MAX(AGE) AS MAXAGE
-- FROM CUSTOMER
-- GROUP BY ADDRESS
-- HAVING MAXAGE > 15; 

SELECT ADDRESS, NAME, MAX(AGE) AS MAXAGE
FROM CUSTOMER
GROUP BY ADDRESS, NAME
HAVING MAXAGE > 15;






