CREATE DATABASE CONSTRAINT_TEST;

USE CONSTRAINT_TEST;

CREATE TABLE TEST(
	ID INT NOT NULL,
    NAME VARCHAR(30),
    RESERVEDATE DATE,
    ROOMNUM INT
);

DESC TEST;

INSERT INTO TEST(ID, NAME, RESERVEDATE, ROOMNUM)
VALUES(1, '이태현', '2025-02-16', 1108);

SELECT * FROM TEST;

ALTER TABLE TEST
ADD NULL_TEST VARCHAR(30) NOT NULL;

INSERT INTO TEST(ID, NAME, RESERVEDATE, ROOMNUM, NULL_TEST)
VALUES(2, '홍길동', '2025-02-17', 1109, "한길");


CREATE TABLE TEST1(
	ID INT UNIQUE,
    NAME VARCHAR(30),
    RESERVEDATE DATE,
    ROOMNUM INT
);

DESC TEST1;

INSERT INTO TEST1 (ID, NAME, RESERVEDATE, ROOMNUM)
VALUES(2, '이태현', '2025-02-16', 1108);

SELECT * FROM TEST1;

ALTER TABLE TEST1
ADD CONSTRAINT UNIQUE(ROOMNUM);

UPDATE TEST1
SET ROOMNUM = 9999
WHERE ID = 2;

CREATE TABLE TEST2(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    RESERVEDATE DATE,
    ROOMNUM INT
);

INSERT INTO TEST2(ID, NAME, RESERVEDATE, ROOMNUM)
VALUES(1, '홍길동', '2025-02-16', 1108);

INSERT INTO TEST2(ID, NAME, RESERVEDATE, ROOMNUM)
VALUES(2, '나길동', '2025-02-17', 1109);

SELECT * FROM TEST2;

DESC TEST2;

ALTER TABLE TEST1
DROP INDEX ROOMNUM;

DESC TEST1;

CREATE TABLE TEST3(
	ID INT,
    PARENTID INT,
    FOREIGN KEY(PARENTID) REFERENCES TEST2(ID)
);

DESC TEST3;

INSERT INTO TEtest3ST3
VALUES(1, 50);

INSERT INTO TEST3
VALUES(2, 100);

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;


CREATE TABLE DEFAULT_TABLE(
	ID INT,
    NAME VARCHAR(30) DEFAULT '익명',
    RESERVEDATE DATE,
    ROOMNUM INT
);

INSERT INTO DEFAULT_TABLE(ID, RESERVEDATE, ROOMNUM)
VALUES(1, '2025-02-16', 1108);

SELECT * FROM DEFAULT_TABLE;


CREATE DATABASE TEST_DB;
USE TEST_DB;

CREATE TABLE PRI_KEY(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    RESERVEDATE DATE,
    ROOMNUM INT
);

CREATE TABLE REF_KEY(
	ID INT,
    PARENTID INT,
    FOREIGN KEY(PARENTID) REFERENCES PRI_KEY(ID) ON UPDATE CASCADE
);

INSERT INTO PRI_KEY(ID, NAME, RESERVEDATE, ROOMNUM)
VALUES(3, '이태현', '2025-02-16', 1108);

SELECT * FROM PRI_KEY;
SELECT * FROM REF_KEY;

INSERT INTO REF_KEY(ID, PARENTID)
VALUES(1, 3);

UPDATE PRI_KEY
SET ID = 15
WHERE ID = 1;





