# C(CREATE) R(READ) U(UPDATE) D(DELETE)

CREATE DATABASE BOOKS_DB;
USE BOOKS_DB;

CREATE TABLE AUTHORS(
	AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(100),
    NATIONALITY VARCHAR(50)
);

INSERT INTO AUTHORS
VALUES (1, '앙투안 드 생텍쥐페리', '프랑스'),
	   (2, '조앤 K. 롤링', '영국'),
	   (3, '조지 오웰', '영국'),
	   (4, '칼 세이건', '미국'),
	   (5, 'J.R.R. 톨킨', '영국');
      
CREATE TABLE BOOKS(
	BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(100),
    AUTHOR_ID INT,
    GENRE VARCHAR(50),
    PUBLICATION_YEAR INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

INSERT INTO BOOKS
VALUES (1, '어린 왕자', 1, '소설', 1943),
	   (2, '해리 포터와 마법사의 돌', 2, '판타지', 1997),
       (3, '1984', 3, '소설', 1949),
       (4, '코스모스', 4, '과학', 1980),
       (5, '반지의 제왕', 5, '판타지', 1954);
       
SELECT TITLE, AUTHOR_NAME, NATIONALITY
FROM BOOKS B
INNER JOIN AUTHORS A
ON B.AUTHOR_ID = A.AUTHOR_ID;

SELECT TITLE, AUTHOR_NAME
FROM BOOKS B
INNER JOIN AUTHORS A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE NATIONALITY = '영국';

SELECT TITLE, AUTHOR_NAME
FROM BOOKS B
INNER JOIN AUTHORS A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE GENRE = '소설';

INSERT INTO AUTHORS
VALUES (6, '김영하', '대한민국');

INSERT INTO BOOKS
VALUES (6, '살인자의 소거법', 6, '소설', 2013);

UPDATE BOOKS
SET PUBLICATION_YEAR = 1981
WHERE TITLE = '코스모스';

UPDATE AUTHORS
SET NATIONALITY = '한국'
WHERE AUTHOR_ID = 6;

DELETE FROM BOOKS
WHERE TITLE = '1984';

DELETE FROM BOOKS
WHERE AUTHOR_ID = 4;

DELETE FROM AUTHORS
WHERE AUTHOR_ID = (SELECT AUTHOR_ID
				   FROM AUTHORS
                   WHERE AUTHOR_NAME = '칼 세이건');

SELECT AUTHOR_NAME, COUNT(B.BOOK_ID) "BOOKS_COUNT"
FROM AUTHORS A
INNER JOIN BOOKS B
ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_NAME;

SELECT AUTHOR_NAME, COUNT(B.BOOK_ID) "BOOKS_COUNT"
FROM AUTHORS A
INNER JOIN BOOKS B
ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_NAME
ORDER BY BOOKS_COUNT DESC
LIMIT 1;

SELECT TITLE, AUTHOR_NAME
FROM BOOKS B
INNER JOIN AUTHORS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE PUBLICATION_YEAR > (SELECT AVG(PUBLICATION_YEAR)
						  FROM BOOKS);

SELECT TITLE, AUTHOR_NAME, PUBLICATION_YEAR
FROM BOOKS B
INNER JOIN AUTHORS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE (GENRE, PUBLICATION_YEAR) IN (SELECT GENRE, MIN(PUBLICATION_YEAR)
						            FROM BOOKS
                                    GROUP BY GENRE);

SELECT AUTHOR_NAME, COUNT(*) "NATIONALITY"
FROM BOOKS B
INNER JOIN AUTHORS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE GENRE = '소설'
GROUP BY AUTHOR_NAME, NATIONALITY;

SELECT AUTHOR_NAME
FROM BOOKS B
INNER JOIN AUTHORS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE PUBLICATION_YEAR = (SELECT MAX(PUBLICATION_YEAR)
						  FROM BOOKS);
                          
SELECT TITLE, MIN(PUBLICATION_YEAR) "PUBLICATION_YEAR"
FROM BOOKS B
INNER JOIN AUTHORS A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE NATIONALITY = '영국'
GROUP BY TITLE
ORDER BY PUBLICATION_YEAR
LIMIT 1;

CREATE TABLE PUBLISHERS (
	PUBLISHER_ID INT PRIMARY KEY,
    PUBLISHER_NAME VARCHAR(100),
    LOCATION VARCHAR(100)
);

INSERT INTO PUBLISHERS
VALUES (1, '민음사', '서울'),
	   (2, '문학동네', '파주'),
       (3, '창비', '서울'),
       (4, '사이언스북스', '서울'),
       (5, '황금가지', '파주');

ALTER TABLE BOOKS
ADD COLUMN PUBLISHER_ID INT;

ALTER TABLE BOOKS
ADD	FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (PUBLISHER_ID);

UPDATE BOOKS SET PUBLISHER_ID = 1
WHERE BOOK_ID = 1;
UPDATE BOOKS SET PUBLISHER_ID = 2
WHERE BOOK_ID = 2;
UPDATE BOOKS SET PUBLISHER_ID = 3
WHERE BOOK_ID = 3;
UPDATE BOOKS SET PUBLISHER_ID = 4
WHERE BOOK_ID = 4;
UPDATE BOOKS SET PUBLISHER_ID = 4
WHERE BOOK_ID = 6;
       
SELECT TITLE, AUTHOR_NAME
FROM BOOKS B
JOIN AUTHORS A 
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN PUBLISHERS P 
ON B.PUBLISHER_ID = P.PUBLISHER_ID
WHERE P.LOCATION = '서울';
       
SELECT PUBLISHER_NAME P, COUNT(BOOK_ID) AS BOOK_COUNT
FROM PUBLISHERS P
LEFT JOIN BOOKS B
ON B.PUBLISHER_ID = P.PUBLISHER_ID
GROUP BY P.PUBLISHER_NAME;

SELECT PUBLISHER_NAME, COUNT(BOOK_ID) AS BOOK_COUNT
FROM PUBLISHERS P
LEFT JOIN BOOKS B
ON P.PUBLISHER_ID = B.PUBLISHER_ID
GROUP BY P.PUBLISHER_NAME
ORDER BY BOOK_COUNT DESC
LIMIT 1;

SELECT AUTHOR_NAME, COUNT(DISTINCT B.PUBLISHER_ID) AS PUBLISHER_COUNT
FROM AUTHORS A
LEFT JOIN BOOKS B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_NAME;

SELECT TITLE, AUTHOR_NAME, PUBLICATION_YEAR
FROM BOOKS B
JOIN AUTHORS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN PUBLISHERS P ON B.PUBLISHER_ID = P.PUBLISHER_ID
WHERE LOCATION = '파주'
ORDER BY PUBLICATION_YEAR DESC
LIMIT 1;

SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;
SELECT * FROM PUBLISHERS;
